---
title: "Hairdresser_Matching"
author: "Jonathan Karl"
date: "2024-01-02"
output: html_document
---

# Setup

```{r}
rm(list = ls())

# Prevent scientific notation
knitr::opts_knit$set(options(scipen=999))

# Install and load all the packages that will be used for analysis
pkgs <- c("tidyverse", "googlesheets4", "lubridate")

miss_pkgs <- pkgs[!pkgs %in% installed.packages()[,1]] # vector of missing packages
if(length(miss_pkgs)>0){
  install.packages(miss_pkgs)
}
invisible(lapply(pkgs,library,character.only=TRUE))

# Clear our memory by removing objects that are no longer needed.
rm(miss_pkgs, pkgs)
```

# Read the data

```{r}
baseline_data <- read.csv("Data Exports/vcf2_rct_baseline_caregivers_clean.csv")
```

# Playground

- Plan for tracking match between hairdresser<>participant (also export to Gsheets so that Isaac can mark which participant whose hairdresser rejected has been informed)
- By FO --> Match with Hairdressers (who is (not) ineligible). What is the rate of ineligibility?

```{r}

temp_data <- baseline_data %>% 
  filter(cluster_treatment_group %in% c("Online_Offline", "Offline_Only"))

temp_data1 <- baseline_data %>% 
  filter(!(cluster_treatment_group %in% c("Online_Offline", "Offline_Only")))

phonenumbers_correct_group <- unique(temp_data$B11a_phonenumber)

mean(table(temp_data$B11a_phonenumber))
mean(table(temp_data1$B11a_phonenumber))

sort(table(temp_data$B11a_phonenumber), decreasing = T)
sort(table(temp_data1$B11a_phonenumber), decreasing = T)

mean(temp_data1$B11a_phonenumber %in% phonenumbers_correct_group)


temp <- table(temp_data$B11a_phonenumber) > 1
names(temp[temp])


# Which hairdressers were named across treatment groups>
cross_group_hairdressers_phone_numbers <- baseline_data %>% 
  group_by(B11a_phonenumber, cluster_treatment_group) %>% 
  summarise(n = n(), .groups = "drop_last") %>% summarise(n = n()) %>% 
  filter(n > 1) %>% drop_na() %>% pull(B11a_phonenumber)

baseline_data %>% 
  filter(B11a_phonenumber %in% cross_group_hairdressers_phone_numbers) %>% 
  group_by(B11a_phonenumber, cluster_treatment_group) %>% 
  summarise(n = n()) %>% 
  mutate(majority = max(n)) %>% mutate(majority = (n == majority) & sum(n %in% majority) == 1)
  
```
